### ISSUE TITLE
Laravel 5.5 compatibility

### ISSUE THREAD

**Issue by netopvh** [owen-it/laravel-auditing#300]
Is this package compatible with laravel 5.5?

**Comment by mbaeuerle** [comment]
We successfully used it in laravel 5.5 but you have to specifiy `OwenIt\Auditing\AuditingServiceProvider::class`in your `config/app.php` even though the docs state that it's not necessary with Laravel 5.5.

**Comment by quetzyg** [comment]
@mbaeuerle, according to [this](https://laravel-news.com/package-auto-discovery), you shouldn't have to.

**Comment by mbaeuerle** [comment]
I tried that, but unfortunately it didn't work without specifying the service provider.

The first problem that arises is the missing artisan commands for auditing (`php artisan auditing:install`)

And even when using the service provider just for installing `auditing`, there is an exception when using `auditing` afterwards without the provider:
```php
    "message": "Target [OwenIt\\Auditing\\Contracts\\Auditor] is not instantiable.",
    "status_code": 500,
    "error_id": "a01eba45a0b249a7b013d2af27c5c6bb",
    "debug": {
        "line": 918,
        "file": "/var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php",
        "class": "Illuminate\\Contracts\\Container\\BindingResolutionException",
        "trace": [
            "#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->notInstantiable('OwenIt\\\\Auditing...')",
            "#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('OwenIt\\\\Auditing...')",
            "#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('OwenIt\\\\Auditing...', Array)",
            "#3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\\Container\\Container->make('OwenIt\\\\Auditing...', Array)",
            "#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1195): Illuminate\\Foundation\\Application->make('OwenIt\\\\Auditing...')",
            "#5 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(159): Illuminate\\Container\\Container->offsetGet('OwenIt\\\\Auditing...')",
            "#6 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(128): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('OwenIt\\\\Auditing...')",
            "#7 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()",
            "#8 /var/www/vendor/owen-it/laravel-auditing/src/AuditableObserver.php(38): Illuminate\\Support\\Facades\\Facade::__callStatic('execute', Array)",
```

**Comment by quetzyg** [comment]
What version are you using, 4.1?

**Comment by mbaeuerle** [comment]
Yes I am using laravel-auditing version `4.1.2`

**Comment by rorc** [comment]
Similar error:
```
Type error: Argument 1 passed to OwenIt\Auditing\AuditableObserver::updated() must be an instance of OwenIt\Auditing\Contracts\Auditable, instance of App\Order given
```
App\Order is my model.

**Comment by quetzyg** [comment]
@rorc, that has nothing to do with Laravel 5.5. Read the documentation on how to use this library.

**Comment by rorc** [comment]
Sry, i forgot implementing `AuditableContract` 😆

**Comment by quetzyg** [comment]
@mbaeuerle, I'm unable to reproduce the issue you're having.

Here are the steps.

Create a new Laravel 5.5 project:
```sh
composer create-project --prefer-dist laravel/laravel laravel55
```

Install latest Laravel Auditing version:
```sh
cd laravel55
composer require owen-it/laravel-auditing
```

Output of the previous command:
```sh
Using version ^4.1 for owen-it/laravel-auditing
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing owen-it/laravel-auditing (v4.1.2): Loading from cache
owen-it/laravel-auditing suggests installing laravelista/lumen-vendor-publish (Needed to publish the package configuration in Lumen)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: owen-it/laravel-auditing
Package manifest generated successfully.
```

Run the install command:
```sh
php artisan auditing:install
```

Output of the previous command:
```sh
Publishing the config files
Publishing the migration file
Successfully installed Laravel Auditing! Enjoy :)
```

**Comment by oscarnevarezleal** [comment]
For lumen, you have to add this line in bootstrap/app.php

`$app->register(OwenIt\Auditing\AuditingServiceProvider::class);`

**Comment by andreshg112** [comment]
In case anyone is doing some testing, this is needed:
![imagen](https://user-images.githubusercontent.com/15859884/57560144-95d43f80-734a-11e9-879d-a518c63e8a04.png)
