### ISSUE TITLE
Failed to run php artisan vendor:publish --provider OwenIt\Auditing\AuditingServiceProvider --tag=migrations

### ISSUE THREAD

**Issue by zietbukuel** [owen-it/laravel-auditing#826]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10
| Package version   | 13.0
| PHP version       | 8.1

#### Actual Behaviour

I'm getting the following error message after running `php artisan vendor:publish --provider OwenIt\Auditing\AuditingServiceProvider --tag=migrations`

```
PHP Fatal error:  Uncaught BadMethodCallException: Method Illuminate\Foundation\Application::configure does not exist. in /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
Stack trace:
#0 /var/www/html/bootstrap/app.php(55): Illuminate\Foundation\Application->__call('configure', Array)
#1 /var/www/html/artisan(20): require_once('/var/www/html/b...')
#2 {main}
  thrown in /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 113

Fatal error: Uncaught BadMethodCallException: Method Illuminate\Foundation\Application::configure does not exist. in /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
Stack trace:
#0 /var/www/html/bootstrap/app.php(55): Illuminate\Foundation\Application->__call('configure', Array)
#1 /var/www/html/artisan(20): require_once('/var/www/html/b...')
#2 {main}
  thrown in /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 113
```

#### Expected Behaviour

I'd expect this to install the migration files.

**Comment by zietbukuel** [comment]
Never mind, it worked after a trying a few times...

**Comment by gilbok** [comment]
I am experiencing the same issue.
- Laravel 10
- PHP 8.2.8
