### ISSUE TITLE
Class "Request" not found

### ISSUE THREAD

**Issue by robin-trigg** [owen-it/laravel-auditing#888]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 10.0.2
| Package version   | 13.6.3
| PHP version       | 8.2.12

#### Actual Behaviour

Tests fail after upgrading to 13.6.3 from 13.5.

#### Expected Behaviour

Tests pass.

#### Steps to Reproduce

Some tests fail with this stack trace:

```
testing.ERROR: Class "Request" not found {"exception":"[object] (Error(code: 0): Class \"Request\" not found at vendor/owen-it/laravel-auditing/src/Resolvers/UrlResolver.php:29)

[stacktrace]
#0 vendor/owen-it/laravel-auditing/src/Resolvers/UrlResolver.php(21): OwenIt\\Auditing\\Resolvers\\UrlResolver::resolveCommandLine()
#1 [internal function]: OwenIt\\Auditing\\Resolvers\\UrlResolver::resolve(Object(App\\Models\\Referral))
#2 vendor/owen-it/laravel-auditing/src/Auditable.php(410): call_user_func(Array, Object(App\\Models\\Referral))
#3 vendor/owen-it/laravel-auditing/src/Auditable.php(349): App\\Models\\Referral->runResolvers()
#4 vendor/owen-it/laravel-auditing/src/Auditor.php(76): App\\Models\\Referral->toAudit()
#5 vendor/illuminate/support/Facades/Facade.php(355): OwenIt\\Auditing\\Auditor->execute(Object(App\\Models\\Referral))
#6 vendor/owen-it/laravel-auditing/src/Listeners/RecordCustomAudit.php(11): Illuminate\\Support\\Facades\\Facade::__callStatic('execute', Array)
#7 vendor/illuminate/events/Dispatcher.php(478): OwenIt\\Auditing\\Listeners\\RecordCustomAudit->handle(Object(App\\Models\\Referral))
#8 vendor/illuminate/events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('OwenIt\\\\Auditing...', Array)
#9 vendor/illuminate/events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('OwenIt\\\\Auditing...', Array, false)
#10 vendor/illuminate/support/Facades/Facade.php(355): Illuminate\\Events\\Dispatcher->dispatch('OwenIt\\\\Auditing...', Array)
#11 vendor/owen-it/laravel-auditing/src/Auditable.php(771): Illuminate\\Support\\Facades\\Facade::__callStatic('dispatch', Array)
#12 vendor/owen-it/laravel-auditing/src/Auditable.php(683): App\\Models\\Referral->dispatchRelationAuditEvent('affiliationEnqu...', 'attach', Object(Illuminate\\Database\\Eloquent\\Collection), Object(Illuminate\\Database\\Eloquent\\Collection))
```

#### Possible Solutions

Merge https://github.com/owen-it/laravel-auditing/pull/887

**Comment by MortenDHansen** [comment]
Should be fixed with latest release
